"""empty message

Revision ID: 673215bcf84d
Revises: 
Create Date: 2025-01-27 17:39:05.100828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673215bcf84d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('stock', sa.String(length=250), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    # ### end Alembic commands ###
