"""Atributos

Revision ID: e415d23cbb6c
Revises: d88223dcd109
Create Date: 2025-01-29 13:05:25.214583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e415d23cbb6c'
down_revision = 'd88223dcd109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('tipo_dato', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atributo_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_atributo', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_atributo'], ['atributo.id'], ),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valor_atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_atributo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['id_atributo'], ['atributo.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valor_atributo')
    op.drop_table('atributo_categoria')
    op.drop_table('atributo')
    # ### end Alembic commands ###
